# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SocialBodhi' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SocialBodhi

  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'


  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  target 'SocialBodhiTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SocialBodhi-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SocialBodhi-tvOS

  target 'SocialBodhi-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
